### ISSUE TITLE
[BUG] Sleeping with auto sort to chest on breaks smelter and charcoal furnace

### ISSUE THREAD

**Issue by Varinius** [valheimPlus/ValheimPlus#244] opened 2021-03-05 22:07 UTC
- OS: Windows Client
- Valheim Game Version 0.147.3
 - Mod Version 0.9.3

**Describe the bug**
Charcoal furnace and smelter do not craft/smelt overnight with the auto sort to chest setting on. After waking up they stop producing coal/metal ingots at all while consuming the ingredients. I as the host could not see any coal produced, while my friend saw 3 produced instead of 13.

**To Reproduce**
1. Enable furnace and smelter auto depositing to chest in config (I also changed the speed and max item values but don't think they're the problem)
2. Start game and fill the smelter/charcoal furnace
3. Sleep
4. The smelting and coal production no longer works properly

**Expected behavior**
Smelting is sped up overnight like vanilla, and production/sorting doesn't delete the product of smelting

**Comment by nxPublic** [comment] 2021-03-06 07:23
We will investigate this issue.

**Comment by nxPublic** [comment] 2021-03-06 08:42
I cannot reproduce this issue at all. Neither on my server locally, neither on a remote one with other people on. Single player works fine as well.

I'd suggest you check the other chests you might have just missed it.

**Comment by fabyx** [comment] 2021-03-06 10:35
+1 same bug here, with very erratic behaviour on auto deposite. 
Had to destroy/rebuild smelter & chest multiple time to make it works. No other chest in the range (10m) => metal definitly lost.

**Comment by xiaodoudou** [comment] 2021-03-06 11:44
Hey @Varinius could you provide your config and your friend config?
Hey @fabyx could you provide yours too?

Thank you!

**Comment by Varinius** [comment] 2021-03-06 12:53
here is my config, had to change to txt to uplaod 
[valheim_plus.txt](https://github.com/valheimPlus/ValheimPlus/files/6095335/valheim_plus.txt)

**Comment by fabyx** [comment] 2021-03-06 13:40
Had to disable auto-deposite as you can see in this config file. Everything is the same as when I had the bug. 

[valheim_plus - Copie.txt](https://github.com/valheimPlus/ValheimPlus/files/6095393/valheim_plus.-.Copie.txt)

**Comment by rez6** [comment] 2021-03-06 16:27
noticing something as well, packing smelter/kiln full then portaling elsewhere, waiting a few and going back, 2 things happen, coal is on ground and smelter either eats the ore and no additional ingots were made. 

when standing near or in the town it works, things are sorted randomly but it works, using 5m distance~ assuming someone needs to be within distance

**Comment by rez6** [comment] 2021-03-07 06:53
now im seeing the bug OP was talking about, its something to do with desync im guessing, iron being made right in front of me showed up nowhere and my iron stack stayed at 27, using 5m radius and no other boxes nearby, my friend sees the iron that was made in the box though. 

made a quick 1min youtube video showing it, afterwards i asked if he saw the stuff being made and he did, and he saw me moving it around as i was moving ore?? maybe just server related?

https://youtu.be/DkoGTb205iM

**Comment by xiaodoudou** [comment] 2021-03-08 10:30
Did you have any over chests around you could check?
More base on the current code; if you have that effect w/o an item it means it found a chest (maybe not the closest one)

**Comment by rez6** [comment] 2021-03-08 16:41
nothing else was near, after a server restart the iron was able to be seen, so its server related or something

**Comment by xiaodoudou** [comment] 2021-03-08 16:45
@rez6 where that Iron was able to be seen; on the floor or inside the chest?

**Comment by rez6** [comment] 2021-03-08 16:51
it was inside one of the chests that was empty when i was looking before

**Comment by nxPublic** [comment] 2021-03-20 11:00
This should be addressed in 0.9.6.

I am closing this issue and would ask anyone reading this after 0.9.6 release to open a new issue regarding this if it is still broken.

**Closed by nxPublic** 2021-03-20 11:00 UTC
Labels: bug, question
