### ISSUE TITLE
[BUG] Furnace/Kiln/Smelter autoDeposit / Sync

### ISSUE THREAD

**Issue by Mannot74** [valheimPlus/ValheimPlus#356] opened 2021-03-13 21:17 UTC
- **OS:** Windows Client
- **Valheim Game Version:** 0.147.3
- **V+ Mod Version:** 0.9.5

First of all, sorry for my bad english. Config file V+ attached in TXT

**Describe the bug**

I activated the deposit of items in a nearby chest for the smelter, the furnace and the kiln.

Everything works for me hosting the game from steam windows.

The problem being when a player connects to my game, the items automatically deposited in the chests near the smelter, furnace, kiln, are not updated for the other player.

Example, the kiln creates and deposits 3 coal in the dedicated chest, for me I see the 3 coal and the other player does not see them.
the other player tried to place the wood in the kiln, to replace the dedicated chest, same problem, I see the items being added but not the other player.

We tried the opposite, the other player hosted the game (with the same game version, V + and config)

At this moment, everything works for him, but I no longer see the items being added to the dedicated chests.

Details: When I host the game, and the other player is logged in, if I open one of the dedicated chests, there is like an update of the dedicated chests and the other player can see the real number of items in chests. Once done, the other player no longer see the items being added until I open the chests myself.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Configure V+ config for kiln/furnace/smelter placed items in near chest
2. Host game with steam
3. Put wood in kiln, watch chest when there is some coal
4. Ask other player to connect to the game and open chest for see if there is some coal

**Expected behavior**

Expect all players can see same items on nearby chests when autoDeposit=true

**Troubleshooting**

Reinstalled the game. re-download mods, reconfigured.
Destroyed and replaced the chests.
Logged into the game hosted by the other player

**Additional context**

BepInExPack Valheim
Equipment and Quick Slots-92-1-0-5-1614994001

[valheim_plus.txt](https://github.com/valheimPlus/ValheimPlus/files/6135592/valheim_plus.txt)

**Comment by EASYUK-DarrenWhite** [comment] 2021-03-14 16:10
Under the [Server] section, make sure the following are set to true

[Server]
enforceMod=true
serverSyncsConfig=true

**Comment by Mannot74** [comment] 2021-03-14 16:39
> Under the [Server] section, make sure the following are set to true
> 
> [Server]
> enforceMod=true
> serverSyncsConfig=true

Thanks for the answer but the section [Server] is already activated with the following parameters : 
enabled=true
enforceMod=true
serverSyncsConfig=true

**Comment by Rycochet** [comment] 2021-03-14 17:10
Seen the same thing here - config is correct, running the game as a dedicated server locally on my machine - I get the correct chest contents, a remote player does not. If I move the items from one slot in the chest to another the other player now sees it correctly (as expected). Seems to be something going wrong in the data sync.

**Comment by Mannot74** [comment] 2021-03-14 18:08
@Rycochet Can you please test to open chest, watch how much items, wait 20 seconds, and ask the other player to open and check contents ?

**Comment by Rycochet** [comment] 2021-03-14 20:36
> @Rycochet Can you please test to open chest, watch how much items, wait 20 seconds, and ask the other player to open and check contents ?

Did that as part of the testing (from a spinning wheel) - it wouldn't update even after a delay - not going to get a chance to play again for a couple of days, but have a feeling that it also happened when I was still in the correct chunk and the other player came in through a portal.

**Comment by Mixone-FinallyHere** [comment] 2021-03-19 17:26
These are likely due to incomptabilities with the inventory mods you guys are using

Equipment and Quick Slots and Equipment Wheel both affect inventory

SO does ours, please test if the bug happens without the other mods so that we can know if it really is a bug or not.

**Comment by Rycochet** [comment] 2021-03-19 19:29
> These are likely due to incomptabilities with the inventory mods you guys are using

Not using any inventory mods here at least - we've got a plan for testing mods over the weekend, and will see if it can be tracked down (given the update issues with the amount of terraforming at the location we noticed this I do feel it's sync related)

**Comment by nxPublic** [comment] 2021-03-20 10:43
This has been addressed in 0.9.6

**Comment by mdcohen** [comment] 2021-03-20 10:45
Take it easy, Cowboy.

**Comment by ethanjhuang** [comment] 2021-03-23 02:21
i have same issue too.

**Comment by Mannot74** [comment] 2021-03-23 02:30
> i have same issue too.

We need to wait patch 0.9.6 i think.

**Comment by Mannot74** [comment] 2021-03-25 09:31
I tried with the new V+ update 0.9.6 (on server hosting)

First, I only configured the new server-side V+ config file.
The auto deposit, and the auto fuel not working, I thought the server was not forcing the client's config.
So I configured the V + config file on the client side too, and the auto deposit / auto fuel seems not to work.

I will try it on Steam Local host now.

**Comment by Mannot74** [comment] 2021-03-25 09:37
I tried only on Steam Local Host.
It seems not to work.
[V+ config 0.9.6.txt](https://github.com/valheimPlus/ValheimPlus/files/6203590/V%2B.config.0.9.6.txt)

V+ config file attached.

**Comment by healiha** [comment] 2021-03-25 10:47
@Mannot74 thanks for the report.

I'll try reproducing that on my side with your settings.

One thing you could try is increasing is the range check to 3 or maybe 4 to see if it still happens.

Since distance between objects is calculated using the center of each objects, the container would have to be stuck to the game object.

Waiting for your feeddback!

**Comment by Rycochet** [comment] 2021-03-25 10:52
Yeah - the smelter, furnace, and kiln - all are over 3m across (over 1.5m radius) themselves, plus the dimensions of the chest - having it at 3m works, while 2m doesn't. This might be a bit illogical to some people (and not others) - so maybe add to the comment in the config file saying something like "this is from the middle of the source to the middle of the chest" ?

**Closed** 2021-03-25 11:43 UTC
Labels: bug, question

**Comment by Mannot74** [comment] 2021-03-25 12:50
@healiha @Rycochet 

Thank you for your answers.
I tried with range 5 and it works with one or more chests.
I'm waiting for another player to connect to the server to test the auto deposit / auto fuel sync.

**Comment by ethanjhuang** [comment] 2021-03-25 13:29
I have try auto deposit / auto fuel sync almost 2 days. And it's work fine for me. :D

**Comment by Mannot74** [comment] 2021-03-25 13:33
> I have try auto deposit / auto fuel sync almost 2 days. And it's work fine for me. :D

I imagine with other connected players ? ;)

**Comment by healiha** [comment] 2021-03-25 13:35
I've been running a server with both features enabled and it works well with other players around, I've made sure it would 🙂

**Comment by Mannot74** [comment] 2021-03-25 13:40
@healiha Thank you for the info. I will wait to test with other players to confirm ;)

**Comment by ethanjhuang** [comment] 2021-03-25 13:40
> > I have try auto deposit / auto fuel sync almost 2 days. And it's work fine for me. :D
> 
> I imagine with other connected players ? ;)

Yes, with my 4 friends.
