### ISSUE TITLE
[BUG] Losing items when joining a server that has a smaller inventory space than the previous server one was in

### ISSUE THREAD

**Issue by nicholaiTukanov** [valheimPlus/ValheimPlus#336] opened 2021-03-12 22:33 UTC
- **OS:  Windows Client, Windows Server**
- **Valheim Game Version: 0.147.3**
- **V+ Mod Version: 0.9.4** 

**Describe the bug**

If a player joins a server that has a smaller inventory space than the previous server the player was in, then upon rejoining the server with the larger inventory, the player will find that the items kept in the extra spaces are now gone.

This bug was found when our dedicated server crashed, and the players went to join another server that had a smaller inventory space.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Join a server with an inventory space larger than the default.
2. Store items in the extra spaces.
3. Leave the server and join another one with a smaller-sized inventory.
4. Leave the server and rejoin the one with the larger inventory.

**Expected behavior**

No items are lost upon rejoining the server with the larger inventory space.

**Additional context**

I am pretty sure this happens 

There are some obvious workarounds to this bug:

1. Do not join a server with smaller inventory space.
2. Place the items that are in the extra slots into a chest before logging out.
3. Respawn the items using cheats.

I am pretty sure this bug happens because the character profiles are not stored on the server. That makes actually solving this bug quite difficult, and more on the hands of the game devs. My main goal with this post is to bring awareness to this issue so that people don't lose their items by accident!

**Comment by KleskReaver** [comment] 2021-03-13 01:52
Yep this happened to me, and yep character profiles are 100% stored on local PC

in addition, if you dont want your character to be visually naked on the character select screen, the workaround is to not store your equipped armor in the extra slots as well

I havent tested this but a possible workaround for not losing your items in the extra slots if you accidentally join a vanilla server or local world is to use the same V+ config settings on your client as they are on the server you play on, or at least the same config setting for the player inventory

give it a try :)

**Comment by Mixone-FinallyHere** [comment] 2021-03-19 17:34
I'm sorry, but a minimum of common sense needs to be applied, when you go to a server with smaller inventory, your items are getting destroyed, this is not a bug, it is a user error
Characters are local, not server side as you say

Issues are for reporting issues or making feature requests, since this is not a bug I am closing it

**Closed by Mixone-FinallyHere** 2021-03-19 17:34 UTC
Labels: bug, wontfix

**Comment by nicholaiTukanov** [comment] 2021-03-19 17:56
It's not a user error if the user never knew that it would happen. Common sense only applies if the user knows the bug beforehand, and this issue is most definitely a bug since it is unintended behavior.

Many people don't know about where character profiles are stored. The point of my post was to ensure all players that use V+ understand that character profiles are stored on the client and what the side effects of that are.
