### ISSUE TITLE
Server still shows you are connected even tho you disconnected

### ISSUE THREAD

**Issue by mosbyNO** [valheimPlus/ValheimPlus#123] opened 2021-02-25 10:42 UTC
Hi, not sure if this is a mod issue or an issue with the latest version of the game.

But in my steam gui for servers it shows 1/10 players online even tho after I have logged out (server is hosted by 3rd party and just me and my friend playing there and he is not online).

Also GUI by 3rd party shows 1 player online still after 10-15 min I logged out.

Using 0.9 version on both server and client.

**Comment by MiR4i** [comment] 2021-02-25 10:49
I'm going to assume this is an issue with the latest update to Valheim that was just released, since I see the same thing and have not yet updated v0.9.

**Comment by KenshiHH** [comment] 2021-02-25 11:22
can confirm, its an issue with the new valheim update and not valheimplus.
just tested on a clean server, it always reports the last max current player size since its running als current players

**Comment by radmint** [comment] 2021-02-26 03:43
thank you all for jumping on to confirm the issue with the Valheim update. I'm going to close this issue as won't fix.

**Closed by radmint** 2021-02-26 03:43 UTC
Labels: wontfix

**Comment by Neoony** [comment] 2021-02-26 11:27
Hitfix from Valheim fixed that now, they say  
  
0.146.11  
Quick fix patch for some network issues. Have a nice weekend everybody!  
  
*** Fixed connected player counter (Correctly ending auth sessions)**  
* Fixes instant disconnection issue that some players have experienced.

**Comment by rr222cy** [comment] 2021-02-26 12:12
> 
> 
> Hotfix from Valheim fixed that now, they say
> 
> 0.146.11
> Quick fix patch for some network issues. Have a nice weekend everybody!
> 
> *** Fixed connected player counter (Correctly ending auth sessions) ***
> Fixes instant disconnection issue that some players have experienced.

I can confirm this resolved the issue, so update your servers! 😃
