### ISSUE TITLE
[BUG] unity crash on startup

### ISSUE THREAD

**Issue by Pantro32** [valheimPlus/ValheimPlus#704] opened 2022-06-22 22:30 UTC
- **OS:** [e.g. Windows Client, Windows Server, or Linux Server] windows client
- **Valheim Game Version:** [e.g. 0.4.11, etc]20.3.33
- **V+ Mod Version:** [e.g. 0.9, 0.9.2, etc.]

**Describe the bug**
Game won't start...unity start window pops uo with error message..the game had an update, we just need a new bep file or unity file, since the update.

**To Reproduce**
Just start the game with valheim plus installed and ready to go.

**Expected behavior**

**Troubleshooting**

What steps have you taken to try to fix?

Verified integrity or files, restarted everything... when I delete the valheim plus files the games works just fine.

**Screenshots**

![20220621_144647](https://user-images.githubusercontent.com/108027879/175164783-2c9df233-83fc-4419-ab95-3ebd4850fb3a.jpg)

**Link to [pastebin](https://pastebin.com) containing .cfg configuration if applicable:**

**Additional context**

*Please list any other mods besides V+ that you have installed* here. Add any other context about the problem here.

**Comment by snips86x** [comment] 2022-06-22 22:35
The issue is bepinex not v+, you can download an updated bepinex from thunderstore

**Comment by ich777** [comment] 2022-06-23 11:31
@snips86x but wouldn't it be better that ValheimPlus releases a version that includes the new BepInEx release?

**Comment by schrer** [comment] 2022-06-23 14:01
Some more info about this is in issue #703 and on the V+ discord (can be found on the readme of this repo)
I assume (but don't know) that the V+ guys will create an update with the new bepinex version. For now replacing it manually is your best bet

**Comment by ich777** [comment] 2022-06-23 14:44
@schrer yes, I already know #703 but the preferred way should be that the developers fix this and release a updated package...

This is not a question how to workaround that by updating the BepInEx Package, the issue is more of a thing that should be fixed anyways and that a new package should be released that is actually working... ;)

**Comment by schrer** [comment] 2022-06-23 14:58
@ich777 I absolutely agree with you. But the Valheim update came out 2 days ago and the V+ team is probably doing this as a hobby in their free time. 
Although their communication about this is lacking, a few days time waiting for a fix is something to be expected and absolutely justified IMO.
All I know is that one of the devs has said he started working on it, so we'll see what happens next.

**Comment by katanacrimson** [comment] 2022-06-25 14:41
Likely resolved by the latest release: https://github.com/valheimPlus/ValheimPlus/releases/tag/0.9.9.8-BepInEx

**Closed as completed** 2022-06-27 10:51 UTC
Labels: bug
