### ISSUE TITLE
[FEATURE REQUEST] Sync Map Icons between players

### ISSUE THREAD

**Issue by SerinitySW** [valheimPlus/ValheimPlus#469] opened 2021-03-26 08:09 UTC
I absolutely love the map sync feature, and think it could be improved even more by syncing map icons between players. It would be even more cool if you could sync only certain icons (for example, the house and pickaxe icons) - but I would definitely settle for just general syncing.

**Comment by gnouts** [comment] 2021-03-26 09:15
I think that's a duplicate of https://github.com/valheimPlus/ValheimPlus/issues/50

**Comment by nxPublic** [comment] 2021-03-26 10:48
This suggestion is already added to http://valheim.plus/todo under Map as "Map Marker Sync System".

**Closed by nxPublic** 2021-03-26 10:48 UTC
Labels: feature request
